fetchUser functie aangespast in componenten: ApiService.js, App, AppRoutes.js, Auth, Login.js, PrivateRoutes.js
updated Auth, LoginPage.js en UserList
probleem met het posten en getten van apikey en userId

AuthProvider werkt met Login en logout geeft nog errors:
Error handling response: TypeError: Cannot destructure property 'enabled' of 'undefined' as it is undefined.
    at chrome-extension://cmedhionkhpnakcndndgjdbohmhepckk/scripts/contentscript.js:1327:5
localhost/:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

bundle.js:3643 Error fetching user details:
Error: API key not found in localStorage